"""initial migration

Revision ID: 350ae6dc5153
Revises: 
Create Date: 2026-02-02 16:36:14.482247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '350ae6dc5153'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_archetypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('typical_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ref_archetypes_id'), 'ref_archetypes', ['id'], unique=False)
    op.create_table('ref_emotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('valence', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', 'AMBIGUOUS', name='emotion_valence'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ref_emotions_id'), 'ref_emotions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('graph_path', sa.String(length=255), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dreams_indexed_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_normalized', sa.String(length=100), nullable=False),
    sa.Column('character_type', sa.Enum('KNOWN_PERSON', 'UNKNOWN_PERSON', 'SELF', 'ANIMAL', 'MYTHICAL', 'ABSTRACT', name='character_type'), nullable=True),
    sa.Column('real_world_relation', sa.String(length=100), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=True),
    sa.Column('first_appeared', sa.Date(), nullable=True),
    sa.Column('last_appeared', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name_normalized', name='uq_user_character')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_index('ix_characters_user_id', 'characters', ['user_id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.create_index('ix_chats_user_id', 'chats', ['user_id'], unique=False)
    op.create_table('dream_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dream_series_id'), 'dream_series', ['id'], unique=False)
    op.create_index('ix_dream_series_user_id', 'dream_series', ['user_id'], unique=False)
    op.create_table('dreams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('dream_date', sa.Date(), nullable=False),
    sa.Column('setting', sa.Text(), nullable=True),
    sa.Column('development', sa.Text(), nullable=True),
    sa.Column('ending', sa.Text(), nullable=True),
    sa.Column('emotion_on_waking', sa.String(length=50), nullable=True),
    sa.Column('emotional_intensity', sa.SmallInteger(), nullable=True),
    sa.Column('lucidity_level', sa.Enum('NONE', 'BRIEF', 'PARTIAL', 'FULL', name='lucidity_level'), nullable=True),
    sa.Column('sleep_quality', sa.SmallInteger(), nullable=True),
    sa.Column('ritual_completed', sa.Boolean(), nullable=True),
    sa.Column('ritual_description', sa.Text(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('is_nightmare', sa.Boolean(), nullable=True),
    sa.Column('personal_interpretation', sa.Text(), nullable=True),
    sa.Column('is_indexed', sa.Boolean(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_extraction_done', sa.Boolean(), nullable=True),
    sa.Column('conscious_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('emotional_intensity BETWEEN 1 AND 10', name='check_emotional_intensity'),
    sa.CheckConstraint('sleep_quality BETWEEN 1 AND 5', name='check_sleep_quality'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dreams_dream_date', 'dreams', ['dream_date'], unique=False)
    op.create_index(op.f('ix_dreams_id'), 'dreams', ['id'], unique=False)
    op.create_index('ix_dreams_user_date', 'dreams', ['user_id', 'dream_date'], unique=False)
    op.create_index('ix_dreams_user_id', 'dreams', ['user_id'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_normalized', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('OBJECT', 'PLACE', 'ACTION', 'ANIMAL', 'NATURE', 'BODY', 'OTHER', name='symbol_category'), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=True),
    sa.Column('first_appeared', sa.Date(), nullable=True),
    sa.Column('last_appeared', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name_normalized', name='uq_user_symbol')
    )
    op.create_index(op.f('ix_symbols_id'), 'symbols', ['id'], unique=False)
    op.create_index('ix_symbols_user_id', 'symbols', ['user_id'], unique=False)
    op.create_table('character_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('association_text', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('USER', 'AI_SUGGESTED', name='association_source'), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_character_associations_character_id', 'character_associations', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_associations_id'), 'character_associations', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='chat_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_dream_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_excerpts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('query_type', sa.Enum('PATTERN', 'SYMBOL', 'TIMELINE', 'GENERAL', name='query_type'), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_chat_id', 'chat_messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_table('dream_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dream_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('role_in_dream', sa.Enum('PROTAGONIST', 'ANTAGONIST', 'HELPER', 'OBSERVER', 'TRANSFORMER', 'UNKNOWN', name='role_in_dream'), nullable=True),
    sa.Column('archetype', sa.String(length=100), nullable=True),
    sa.Column('traits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_ai_extracted', sa.Boolean(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('context_note', sa.Text(), nullable=True),
    sa.Column('personal_significance', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dream_id', 'character_id', name='uq_dream_character')
    )
    op.create_index('ix_dream_characters_archetype', 'dream_characters', ['archetype'], unique=False)
    op.create_index('ix_dream_characters_character_id', 'dream_characters', ['character_id'], unique=False)
    op.create_index('ix_dream_characters_dream_id', 'dream_characters', ['dream_id'], unique=False)
    op.create_index(op.f('ix_dream_characters_id'), 'dream_characters', ['id'], unique=False)
    op.create_table('dream_emotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dream_id', sa.Integer(), nullable=False),
    sa.Column('emotion', sa.String(length=50), nullable=False),
    sa.Column('emotion_type', sa.Enum('DURING', 'WAKING', name='emotion_type'), nullable=False),
    sa.Column('intensity', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('intensity BETWEEN 1 AND 10', name='check_emotion_intensity'),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dream_id', 'emotion', 'emotion_type', name='uq_dream_emotion_type')
    )
    op.create_index('ix_dream_emotions_dream_id', 'dream_emotions', ['dream_id'], unique=False)
    op.create_index('ix_dream_emotions_emotion', 'dream_emotions', ['emotion'], unique=False)
    op.create_index(op.f('ix_dream_emotions_id'), 'dream_emotions', ['id'], unique=False)
    op.create_table('dream_series_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('dream_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['dream_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'dream_id', name='uq_series_dream')
    )
    op.create_index('ix_dream_series_members_dream_id', 'dream_series_members', ['dream_id'], unique=False)
    op.create_index(op.f('ix_dream_series_members_id'), 'dream_series_members', ['id'], unique=False)
    op.create_index('ix_dream_series_members_series_id', 'dream_series_members', ['series_id'], unique=False)
    op.create_table('dream_symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dream_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('is_ai_extracted', sa.Boolean(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('context_note', sa.Text(), nullable=True),
    sa.Column('personal_meaning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dream_id', 'symbol_id', name='uq_dream_symbol')
    )
    op.create_index('ix_dream_symbols_dream_id', 'dream_symbols', ['dream_id'], unique=False)
    op.create_index(op.f('ix_dream_symbols_id'), 'dream_symbols', ['id'], unique=False)
    op.create_index('ix_dream_symbols_symbol_id', 'dream_symbols', ['symbol_id'], unique=False)
    op.create_table('dream_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dream_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('is_ai_extracted', sa.Boolean(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dream_id', 'theme', name='uq_dream_theme')
    )
    op.create_index('ix_dream_themes_dream_id', 'dream_themes', ['dream_id'], unique=False)
    op.create_index(op.f('ix_dream_themes_id'), 'dream_themes', ['id'], unique=False)
    op.create_index('ix_dream_themes_theme', 'dream_themes', ['theme'], unique=False)
    op.create_table('symbol_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('association_text', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('USER', 'AI_SUGGESTED', name='association_source'), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbol_associations_id'), 'symbol_associations', ['id'], unique=False)
    op.create_index('ix_symbol_associations_symbol_id', 'symbol_associations', ['symbol_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_symbol_associations_symbol_id', table_name='symbol_associations')
    op.drop_index(op.f('ix_symbol_associations_id'), table_name='symbol_associations')
    op.drop_table('symbol_associations')
    op.drop_index('ix_dream_themes_theme', table_name='dream_themes')
    op.drop_index(op.f('ix_dream_themes_id'), table_name='dream_themes')
    op.drop_index('ix_dream_themes_dream_id', table_name='dream_themes')
    op.drop_table('dream_themes')
    op.drop_index('ix_dream_symbols_symbol_id', table_name='dream_symbols')
    op.drop_index(op.f('ix_dream_symbols_id'), table_name='dream_symbols')
    op.drop_index('ix_dream_symbols_dream_id', table_name='dream_symbols')
    op.drop_table('dream_symbols')
    op.drop_index('ix_dream_series_members_series_id', table_name='dream_series_members')
    op.drop_index(op.f('ix_dream_series_members_id'), table_name='dream_series_members')
    op.drop_index('ix_dream_series_members_dream_id', table_name='dream_series_members')
    op.drop_table('dream_series_members')
    op.drop_index(op.f('ix_dream_emotions_id'), table_name='dream_emotions')
    op.drop_index('ix_dream_emotions_emotion', table_name='dream_emotions')
    op.drop_index('ix_dream_emotions_dream_id', table_name='dream_emotions')
    op.drop_table('dream_emotions')
    op.drop_index(op.f('ix_dream_characters_id'), table_name='dream_characters')
    op.drop_index('ix_dream_characters_dream_id', table_name='dream_characters')
    op.drop_index('ix_dream_characters_character_id', table_name='dream_characters')
    op.drop_index('ix_dream_characters_archetype', table_name='dream_characters')
    op.drop_table('dream_characters')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_chat_id', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_character_associations_id'), table_name='character_associations')
    op.drop_index('ix_character_associations_character_id', table_name='character_associations')
    op.drop_table('character_associations')
    op.drop_index('ix_symbols_user_id', table_name='symbols')
    op.drop_index(op.f('ix_symbols_id'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index('ix_dreams_user_id', table_name='dreams')
    op.drop_index('ix_dreams_user_date', table_name='dreams')
    op.drop_index(op.f('ix_dreams_id'), table_name='dreams')
    op.drop_index('ix_dreams_dream_date', table_name='dreams')
    op.drop_table('dreams')
    op.drop_index('ix_dream_series_user_id', table_name='dream_series')
    op.drop_index(op.f('ix_dream_series_id'), table_name='dream_series')
    op.drop_table('dream_series')
    op.drop_index('ix_chats_user_id', table_name='chats')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index('ix_characters_user_id', table_name='characters')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ref_emotions_id'), table_name='ref_emotions')
    op.drop_table('ref_emotions')
    op.drop_index(op.f('ix_ref_archetypes_id'), table_name='ref_archetypes')
    op.drop_table('ref_archetypes')
    # ### end Alembic commands ###
