"""add universal_meaning to symbols

Revision ID: a94a90e0071a
Revises: 350ae6dc5153
Create Date: 2026-02-06 23:20:15.930326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94a90e0071a'
down_revision: Union[str, Sequence[str], None] = '350ae6dc5153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbols', sa.Column('universal_meaning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symbols', 'universal_meaning')
    # ### end Alembic commands ###
